block-list-secret-scan: []
branch: master
directory:
- .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- terraform
mask: []
output:
- sarif
- junitxml
output-file-path: console,checkov-output/results_junitxml.xml
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
summary-position: top
